config/routes.rb
Copenhagen::Application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }

  root :to => 'home#index'

  resources :locations, only: [:show, :index] do
    resources :checkouts, only: [:index]
  end

  resources :bikes do
    resources :checkouts, only: [:new, :create, :index]
    collection do
      get :offline
      get :fucked
    end
  end

  resources :users, :bikers, except: [:destroy] do
    resources :checkouts, only: [:index]
  end

  resources :checkouts, except: [:edit, :destroy] do
    member do
      delete '', to: 'checkouts#checkin', as: :checkin
    end
  end
end

app/models/biker.rb
class Biker < ActiveRecord::Base

  scope :active, where(active: true)

  has_many :checkouts

  AFFILIATIONS = %w(undergraduate graduate faculty staff).freeze

  validates_inclusion_of :affiliation, in: AFFILIATIONS
  validates_format_of :netid, with: /\A[a-z]{2,5}\d{1,5}\z/

  def has_bike_out?
    !checkouts.checked_out.empty?
  end

  def can_check_out?
    active && !has_bike_out?
  end

  def to_param
    netid
  end

  def to_s
    "#{first_name} #{last_name}"
  end

  # override find so we can search by netid
  def self.find(input)
    input.to_i == 0 ? find_by_netid(input) : super
  end
end

app/controllers/bikers_controller.rb
class BikersController < ApplicationController
  before_filter :require_login
  before_filter :require_admin

  # GET /bikers{.json}
  def index
    @bikers = Biker.order(:netid)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bikers.active.map{ |b| {netid: b.netid, full_name: b.to_s} }}
    end
  end

  # GET /bikers/1{.json}
  # GET /bikers/amk528{.json}
  def show
    @biker = Biker.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @biker }
    end
  end

  # GET /bikers/new
  def new
    @biker = Biker.new
  end

  # GET /bikers/amk528/edit
  def edit
    @biker = Biker.find(params[:netid])
  end

  # POST /bikers{.json}
  def create
    @biker = Biker.new(biker_params)

    respond_to do |format|
      if @biker.save
        format.html { redirect_to @biker, notice: 'Biker was successfully created.' }
        format.json { render json: @biker, status: :created, location: @biker }
      else
        format.html { render action: "new" }
        format.json { render json: @biker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bikers/1{.json}
  def update
    @biker = Biker.find(params[:id])

    respond_to do |format|
      if @biker.update_attributes(biker_params)
        format.html { redirect_to @biker, notice: 'Biker was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @biker.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def biker_params
    params.required(:biker).permit(:email, :netid, :remember_me, :first_name, :last_name, :affilition, :active, :year_of_graduation)
  end
end

app/helpers/bikers_helper.rb
module BikersHelper
end

app/views/bikers/_form.html.erb
<%= form_for(@biker) do |f| %>
  <% if @biker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@biker.errors.count, "error") %> prohibited this biker from being saved:</h2>

      <ul>
      <% @biker.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :netid %><br />
    <%= f.text_field :netid %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :affiliation %><br />
    <%= f.text_field :affiliation %>
  </div>
  <div class="field">
    <%= f.label :year_of_graduation %><br />
    <%= f.number_field :year_of_graduation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bikers/edit.html.erb
<h1>Editing biker</h1>

<%= render 'form' %>

<%= link_to 'Show', @biker %> |
<%= link_to 'Back', bikers_path %>

app/views/bikers/index.html.erb
<h1>Listing bikers</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Netid</th>
    <th>Email</th>
    <th>Affiliation</th>
    <th>Year of graduation</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bikers.each do |biker| %>
  <tr>
    <td><%= biker.first_name %></td>
    <td><%= biker.last_name %></td>
    <td><%= biker.netid %></td>
    <td><%= biker.email %></td>
    <td><%= biker.affiliation %></td>
    <td><%= biker.year_of_graduation %></td>
    <td><%= link_to 'Show', biker %></td>
    <td><%= link_to 'Edit', edit_biker_path(biker) %></td>
    <td><%= link_to 'Destroy', biker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Biker', new_biker_path %>

app/views/bikers/new.html.erb
<h1>New biker</h1>

<%= render 'form' %>

<%= link_to 'Back', bikers_path %>

app/views/bikers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @biker.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @biker.last_name %>
</p>

<p>
  <b>Netid:</b>
  <%= @biker.netid %>
</p>

<p>
  <b>Number of checkouts:</b>
  <%= @biker.checkouts.count %>
  <% unless @biker.checkouts.count == 0 %>
    (<%= link_to 'show', biker_checkouts_path(@biker)%>)
  <% end %>
</p>

<p>
  <b>Email:</b>
  <%= @biker.email %>
</p>

<p>
  <b>Affiliation:</b>
  <%= @biker.affiliation %>
</p>

<p>
  <b>Year of graduation:</b>
  <%= @biker.year_of_graduation %>
</p>


<% if current_user.admin? %>
  <%= link_to 'Edit', edit_biker_path(@biker) %> |
<% end %>
<%= link_to 'Back', bikers_path %>