config/routes.rb
Copenhagen::Application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }

  root :to => 'home#index'

  resources :locations, only: [:show, :index] do
    resources :checkouts, only: [:index]
  end

  resources :bikes do
    resources :checkouts, only: [:new, :create, :index]
    collection do
      get :offline
      get :fucked
    end
  end

  resources :users, :bikers, except: [:destroy] do
    resources :checkouts, only: [:index]
  end

  resources :checkouts, except: [:edit, :destroy] do
    member do
      delete '', to: 'checkouts#checkin', as: :checkin
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_readonly :email, :netid
  attr_protected :password, :password_confirmation, :admin

  devise :database_authenticatable, :rememberable, :trackable, :validatable,
         :token_authenticatable, :timeoutable

  has_many :checkouts, foreign_key: :staffer_id
  belongs_to :location
  belongs_to :biker, foreign_key: :netid, primary_key: :netid

  delegate :first_name, :last_name, :year_of_graduation, :affiliation, :to_param, :to_s, to: :biker

  # override find so we can search by netid
  def self.find(input)
    input.to_i == 0 ? find_by_netid(input) : super
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_login
  before_filter :require_admin

  # GET /users{.json}
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1{.json}
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users{.json}
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1{.json}
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1{.json}
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :netid %><br />
    <%= f.text_field :netid %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :year_of_graduation %><br />
    <%= f.text_field :year_of_graduation %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :affilition %><br />
    <%= f.select :affilition, User::AFFILIATIONS %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing staff</h1>

<table class="table table-striped"  >
  <thead>
    <tr>
      <th>Netid</th>
      <th>Email</th>
      <th>Location</th>
      <th></th>
    </tr>
  </thead>
<% @users.each do |user| %>
  <tr>
    <td><%= link_to user.netid, biker_path(user) %></td>
    <td><%= user.email %></td>
    <td><%= user.location %></td>
    <td>
      <div class="btn-group pull-right">
        <div class="btn dropdown-toggle btn-mini" data-toggle="dropdown">Admin <span class="caret"></span></div>
        <ul class="dropdown-menu">
          <li><%= link_to('<i class="icon-user"></i> View'.html_safe, user) %></li>
          <li><%= link_to('<i class="icon-pencil"></i> Edit'.html_safe, edit_user_path(user)) %></li>
          <li><%= link_to('<i class="icon-trash"></i> Remove'.html_safe, user, method: :delete, data: { confirm: 'Are you sure?' }) %></li>
        </ul>
      </div>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>
  <b>Netid:</b>
  <%= @user.netid %>
</p>

<p>
  <b>First name:</b>
  <%= @user.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @user.last_name %>
</p>

<p>
  <b>Year of graduation:</b>
  <%= @user.year_of_graduation %>
</p>

<p>
  <b>Email address:</b>
  <%= @user.email %>
</p>

<p>
  <b>Location:</b>
  <%= link_to @user.location, @user.location %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>