config/routes.rb
Copenhagen::Application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }

  root :to => 'home#index'

  resources :locations, only: [:show, :index] do
    resources :checkouts, only: [:index]
  end

  resources :bikes do
    resources :checkouts, only: [:new, :create, :index]
    collection do
      get :offline
      get :fucked
    end
  end

  resources :users, :bikers, except: [:destroy] do
    resources :checkouts, only: [:index]
  end

  resources :checkouts, except: [:edit, :destroy] do
    member do
      delete '', to: 'checkouts#checkin', as: :checkin
    end
  end
end

app/models/bike.rb
class Bike < ActiveRecord::Base
  has_many :checkouts
  belongs_to :location

  scope :operational, where(date_offline: nil)
  scope :offline, where("date_offline IS NOT NULL")
  scope :fucked, where(fucked: true)
  scope :checked_out, joins(:checkouts).merge(Checkout.checked_out)
  scope :overdue, -> { joins(:checkouts).merge(Checkout.overdue) }

  delegate :checkin, :due_at, :overdue?, to: :active_checkout, allow_nil: true

  def active_checkout
    checkouts.checked_out.first
  end

  def last_checkout
    checkouts.order('created_at DESC').first
  end

  def checked_out?
    active_checkout != nil
  end

  def checked_out_to
    active_checkout.try(:biker)
  end

  def operational?
    date_offline == nil
  end

  def take_offline!
    update_attribute(:date_offline, Time.now)
  end

  def bring_online!
    update_attribute(:date_offline, nil)
  end

  def to_s
    "##{id} (#{manufacturer} #{model})"
  end
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  before_filter :require_login
  before_filter :require_admin, except: [:index, :show]

  # GET /bikes{.json}
  def index
    @bikes = Bike.order(:id)

    unless current_user.admin?
      @bikes = @bikes.operational.where(location_id: session[:location_id])
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bikes }
    end
  end

  # GET /bikes/offline
  def offline
    @bikes = Bike.offline.order(:id)
    render 'index'
  end

  # GET /bikes/fucked
  def fucked
    @bikes = Bike.fucked.order(:id)
    render 'index'
  end

  # GET /bikes/1{.json}
  def show
    @bike = Bike.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bike }
    end
  end

  # GET /bikes/new
  def new
    @bike = Bike.new
  end

  # GET /bikes/1/edit
  def edit
    @bike = Bike.find(params[:id])
  end

  # POST /bikes{.json}
  def create
    @bike = Bike.new(bike_params)

    respond_to do |format|
      if @bike.save
        format.html { redirect_to @bike, notice: 'Bike was successfully created.' }
        format.json { render json: @bike, status: :created, location: @bike }
      else
        format.html { render action: "new" }
        format.json { render json: @bike.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bikes/1{.json}
  def update
    @bike = Bike.find(params[:id])
    attrs = bike_params

    if @bike.operational? && attrs[:online] == false
      @bike.take_offline!
    elsif !@bike.operational? && attrs[:online] == true
      @bike.bring_online!
    end

    respond_to do |format|
      if @bike.update_attributes(attrs)
        format.html { redirect_to @bike, notice: 'Bike was successfully updated.' }
        format.json { render json: @bike, status: :accepted, location: @bike }
      else
        format.html { render action: "edit" }
        format.json { render json: @bike.errors, status: :unprocessable_entity }
      end
    end
  end

private
  def bike_params
    params.required(:bike).permit(:color, :condition, :location_id, :image_url, :manufacturer, :model, :notes)
  end
end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/views/bikes/_form.html.erb
<%= form_for @bike, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :color, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :color, Bike.pluck(:color).uniq %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :location, :class => 'control-label' %>
    <div class="controls">
      <%= f.collection_select :location_id, Location.all, :id, :name %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :image_url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :image_url, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :manufacturer, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :manufacturer, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :model, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :model, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :notes, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :notes, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                bikes_path, :class => 'btn' %>
  </div>
<% end %>

app/views/bikes/_row.html.erb
<%
  if bike.checked_out?
    row_class = "checked-out info"
  elsif bike.overdue?
    row_class = "overdue error"
  elsif !bike.operational?
    row_class = "offline warning"
  end
%>

<tr class="bike <%= row_class %>">
  <td><%= link_to bike, bike_path(bike) %></td>
  <td><%= bike.color %></td>
  <td><%= bike.checked_out? ? link_to(bike.checked_out_to, bike.checked_out_to) : 'no' %></td>
  <% if current_user.admin? %>
    <td><%= if bike.location then link_to bike.location.name, bike.location else link_to 'Fucked', fucked_bikes_path end %></td>
    <td><%= bike.notes.empty? ? '—' : bike.notes %></td>
  <% end %>
  <td>
    <% if bike.operational? %>
      <% if bike.checked_out? %>
        <%= link_to "check in", checkin_checkout_path(bike.active_checkout), method: :delete %>
      <% else %>
        <%= link_to "check out", new_bike_checkout_path(bike), data: { action: 'create-checkout' } %>
      <% end %>
    <% else %>
      <i>offline</i>
    <% end %>
    <% if current_user.admin? %>
      <div class="btn-group pull-right">
        <%= link_to 'Admin <span class="caret"></span>'.html_safe, '#', class: "btn dropdown-toggle btn-mini", data: { toggle: "dropdown" } %>
        <ul class="dropdown-menu">
          <li><%= link_to '<i class="icon-pencil"></i> Edit'.html_safe, edit_bike_path(bike), data: { action: 'edit' } %></li>
          <% if bike.operational? %>
            <li><%= link_to '<i class="icon-wrench"></i> Take Offline'.html_safe, edit_bike_path(bike), data: { action: 'take-offline' } %></li>
          <% else %>
            <li><%= link_to '<i class="icon-wrench"></i> Bring Online'.html_safe, edit_bike_path(bike), data: { action: 'bring-online' } %></li>
          <% end %>
          <li><%= link_to '<i class="icon-map-marker"></i> Update Location'.html_safe, edit_bike_path(bike), data: { action: 'update-location' } %></li>
        </ul>
      </div>
    <% end %>
  </td>
</tr>

app/views/bikes/edit.html.erb
<%- model_class = Bike -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bikes/index.html.erb
<%- model_class = Bike -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="bikes table table-striped">
  <thead>
    <tr>
      <th>Bike #</th>
      <th>Color</th>
      <th>Checked out?</th>
      <% if current_user.admin? %>
        <th>Location</th>
        <th>Notes</th>
      <% end %>
      <th><!-- checkin / checkout action links --></th>
    </tr>
  </thead>
  <tbody>
    <% @bikes.each do |bike| %>
      <%= render partial: 'row', locals: { bike: bike } %>
    <% end %>
  </tbody>
</table>

<script type="text/javascript">
  window.COPE.bikes = JSON.parse("<%=j @bikes.to_json.html_safe %>");
</script>

app/views/bikes/new.html.erb
<%- model_class = Bike -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bikes/show.html.erb
<%- model_class = Bike -%>
<div class="page-header">
  <h2><%= @bike %></h2>
</div>

<%= image_tag @bike.image_url, class: 'bike-img' %>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:color) %>:</strong></dt>
  <dd><%= @bike.color %></dd>
  <% if current_user.admin? %>
  <dt><strong><%= model_class.human_attribute_name(:notes) %>:</strong></dt>
  <dd><%= @bike.notes %></dd>
  <% end %>
  <dt><strong><%= model_class.human_attribute_name(:location_id) %>:</strong></dt>
  <dd><%= if @bike.location then link_to @bike.location.name, @bike.location end %></dd>
  <dt><strong><%= model_class.human_attribute_name(:manufacturer) %>:</strong></dt>
  <dd><%= @bike.manufacturer %></dd>
  <dt><strong><%= model_class.human_attribute_name(:model) %>:</strong></dt>
  <dd><%= @bike.model %></dd>
</dl>

<div class="form-actions">
  <%= link_to 'Back', bikes_path, :class => 'btn'  %>
  <%= link_to 'Checkout', new_bike_checkout_path(@bike), :class => 'btn' %>
  <%= link_to 'View Checkouts', bike_checkouts_path(@bike), :class => 'btn' %>
  <% if current_user.admin? %>
  <%= link_to 'Edit', edit_bike_path(@bike), :class => 'btn' %>
  <% end %>
</div>