config/routes.rb
Copenhagen::Application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }

  root :to => 'home#index'

  resources :locations, only: [:show, :index] do
    resources :checkouts, only: [:index]
  end

  resources :bikes do
    resources :checkouts, only: [:new, :create, :index]
    collection do
      get :offline
      get :fucked
    end
  end

  resources :users, :bikers, except: [:destroy] do
    resources :checkouts, only: [:index]
  end

  resources :checkouts, except: [:edit, :destroy] do
    member do
      delete '', to: 'checkouts#checkin', as: :checkin
    end
  end
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :latlong, :name, :address, :phone, :hours, :num_helmets

  has_many :bikes
  has_many :checkouts
  has_many :staffers, class_name: :User

  def to_s
    name
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_filter :require_login
  before_filter :require_admin

  # GET /locations{.json}
  def index
    @locations = Location.order(:name)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @locations }
    end
  end

  # GET /locations/1{.json}
  def show
    @location = Location.find(params[:id])
    @bikes = @location.bikes

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location }
    end
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/index.html.erb
<h1>Listing locations</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Bikes out / total</th>
    </tr>
  </thead>
  <tbody>
<% @locations.each do |location| %>
  <tr>
    <td>
      <%= link_to location.name, location %> <%= link_to "(map)", "http://maps.google.com/?q=#{location.latlong}" %>
    </td>
    <td><%= link_to "#{location.bikes.checked_out.count} / #{location.bikes.count}", location_checkouts_path(location) %></td>
  </tr>
<% end %>
  </tbody>
</table>

<br />

app/views/locations/show.html.erb
<h2><%= @location.name %></h2>

<h4>Bikes:</h4>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Info</th>
    </tr>
  </thead>
  <tbody>
<% @bikes.each do |bike| %>
  <tr>
    <td class="<%= 'info' if bike.checked_out?  %>"><%= link_to bike, bike %></td>
  </tr>
<% end %>
  </tbody>
</table>

<div>
  <h4>Helmets: <%= @location.num_helmets %></h4>
</div>

<%= link_to 'Back', locations_path %>